name: Call Random QTS Query Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  call-api-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase GET Function 'qtsquery'
        run: |
          curl -f -L -X GET 'https://npwbxlvcfrawolebzawn.supabase.co/functions/v1/qtsquery' \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
