# .github/workflows/scheduled_random_api_call.yml
name: Every 5 minutes

on:
  # This schedule triggers the workflow every 15 minutes.
  schedule:
    - cron: '*/5 * * * *'
  
  # This allows you to manually run the workflow for testing purposes.
  workflow_dispatch:

jobs:
  call-api-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function with a Random Query
        env:
          PROMPTS_JSON: |
            [
              "What are the core business areas of Quadrate Tech Solutions (quadrate.lk)?",
              "List the key technology stacks used by Quadrate Tech Solutions (quadrate.lk).",
              "Summarize the main products and services offered by Quadrate Tech Solutions (quadrate.lk).",
              "Who are the primary target customers for Quadrate Tech Solutions (quadrate.lk)?",
              "Provide an overview of recent projects completed by Quadrate Tech Solutions (quadrate.lk)."
            ]
        run: |
          ARRAY_LENGTH=$(echo "${PROMPTS_JSON}" | jq 'length')
          RANDOM_INDEX=$(($RANDOM % $ARRAY_LENGTH))
          RANDOM_PROMPT=$(echo "${PROMPTS_JSON}" | jq -r ".[$RANDOM_INDEX]")
          echo "Selected Prompt (index $RANDOM_INDEX): $RANDOM_PROMPT"
          JSON_PAYLOAD=$(jq -n --arg prompt "$RANDOM_PROMPT" '{prompt: $prompt}')
          curl -L -X POST 'https://npwbxlvcfrawolebzawn.supabase.co/functions/v1/quadrate-contact' \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
